# build environment
FROM node:lts-alpine3.10 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV DOMAIN_SERVER=http://nodeback
COPY package.json ./
#COPY package-lock.json ./
RUN npm ci --silent
RUN npm install node-sass --silent
RUN npm install react-scripts@3.3.0 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 88
CMD ["nginx", "-g", "daemon off;"]